### ISSUE TITLE
Data Wrangling und Explorative Datenanalyse zu den Daten

### ISSUE THREAD

**Issue by gabrieltorresgamez** [Immobilienrechner-Challenge/explorative-data-analysis#1]
1) Data Wrangling
1.1) Doppelte Spalten entfernen
1.2) Doppelte Zeilen herausfinden und entfernen
1.3) Fehlende Werte zu Na umwandeln
1.4) Sauberes DataFrame abspeichern

2) Explorative Datenanalyse

**Comment by a-shanmugam** [comment]
Da eda und data wrangling unter meiner Verantwortung liegt, schlage ich folgende Subtasks vor:

1. Im Datenset zur Verfügung gestellte Variablen verstehen und dokumentieren. (Domänenwissen aneignen, gültige Werte, Erwartungswerte, ab wann ein Datenpunkt als Outlier zählt etc. festhalten)
2. Importieren/Einlesen
3. Bereinigen (Doppelte Spalten entfernen, doppelte Zeilen identifizieren und entfernen, fehlende Werte zu Na umwandeln oder imputieren)
4. eda
5. Transformieren (für die Lösung der Fragestellung optimale Datenaufbereitung erstellen)
6. Verknüpfen 
7. Bei Bedarf nochmals eda
8. Sauberes DataFrame abspeichern, evtl. in DB zur Verfügung stellen

Meine Idee ist es, dass ich als Verantwortlicher und daw eingeschriebener Student den Task 2-3 solo übernehme und wir dann den eda Task aufteilen. Den ersten Task würde ich ebenfalls als group effort vielleicht in einer gemeinsamen Session gestalten. 

Dieser Vorschlag gilt als Grundlage zur Diskussion der ersten Teilaufgabe für das Backlog Meeting am 27.09.

**Comment by gabrieltorresgamez** [comment]
@alexfhnw Bitte in kleiner Tasks unterteilen bis Sprintende

**Comment by a-shanmugam** [comment]
Dieser Task wurde in Subtasks unterteilt, somit schliesse ich diesen
