### ISSUE TITLE
eda - create visuals and exploratory statistics

### ISSUE THREAD

**Issue by a-shanmugam** [Immobilienrechner-Challenge/explorative-data-analysis#4]
There are libraries that create stats and graphs automatically as described [here](https://towardsdatascience.com/4-libraries-that-can-perform-eda-in-one-line-of-python-code-b13938a06ae)

**Comment by a-shanmugam** [comment]
Erste Visualisierungen wurden mit `Sweetviz` via `eda_reports.ipynb` unter `Reports/` erstellt. 
ToDo:
- Pandas Profiling
- Visualisierungen verfeinern und erweitern

**Comment by gabrieltorresgamez** [comment]
Pandas Profiling wurde von @7ben18 addiert

**Comment by a-shanmugam** [comment]
Sweetviz Reports wurden nach Bereinigung der Daten aktualisiert und eda.ipynb wurde erstellt, welches die Bereinigung der Zeilendaten behandelt.

**Comment by a-shanmugam** [comment]
Für den Moment sehe ich keinen Bedarf weiterer Visualisierungen.
