### ISSUE TITLE
Neue Daten testen und ggf. integrieren

### ISSUE THREAD

**Issue by gabrieltorresgamez** [Immobilienrechner-Challenge/explorative-data-analysis#8]
Schauen, wie man jetzt mit Fernandos Datensatz umgehen soll.
Erhalten wir bessere Modelle mit den neuen Daten?
Wie wirken sich die neuen Daten auf unseren Datensatz aus?
Sollen wir jetzt einen Aufwand machen die neuen informationen in unseren sauberen Datensatz zu integrieren?

**Comment by gabrieltorresgamez** [comment]
Kleiner Bericht zwischen den Datenunterschieden und EDA Repo ausräumen @alexfhnw

**Comment by gabrieltorresgamez** [comment]
@alexfhnw viel Aufwand, schauen ob man TODO's besser auf die Gruppe aufteilen kann

**Comment by gabrieltorresgamez** [comment]
@alexfhnw was ist hier noch offen?
@gabrieltorresgamez in der dokumentation erklären, was für datensätze im repo "data" sind und für was sie verwendet werden

**Comment by a-shanmugam** [comment]
Hier möchte ich den Text in den Notebooks verfeinern, sodass sich diese gut lesen und als Grundlage für den Bericht genutzt werden können.

**Comment by a-shanmugam** [comment]
Notebooks sind überarbeitet und erste Version des Berichts ist geschrieben
